### ISSUE TITLE
Time box is positioned wrong in Internet Explorer, Edge, and Firefox

### ISSUE THREAD

**Issue by jonathanherdt** [openHPI/videoplayer#26] opened 2017-08-26 17:55 UTC
See picture - the time box sits too low and disappears into the slide preview bar.

![bildschirmfoto_2017-08-22_um_00 45 34](https://user-images.githubusercontent.com/6302908/29743774-69b1435e-8a98-11e7-903d-4d8da6e6660f.png)

**Comment by soldag** [comment] 2017-08-28 07:58
Duplicate of #14

**Closed by soldag** 2017-08-28 07:58 UTC
